---
name: "Newsletters"
guid: "60f478ab-2dd6-4ea0-af10-04d033f75979"
imageUrl: "https://raw.githubusercontent.com/Sanidhya30/Jellyfin-Newsletter/master/logo.png"
version: "0.9.0.1"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Send newsletters for recently added media"
description: "This plugin populates a list of recently added media, sends out the messages to configured clients(email, discord webhook)."
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Newsletters.dll"
  - "SQLitePCL.pretty.dll"
  - "SixLabors.ImageSharp.dll"
changelog: >
  - Bug fix for community rating parsing.
  - Bug fix for parsing runtime.
  FULL CHANGELOG: https://raw.githubusercontent.com/Sanidhya30/Jellyfin-Newsletter/master/CHANGELOG.md
