---
name: "Newsletters"
guid: "60f478ab-2dd6-4ea0-af10-04d033f75979"
imageUrl: "https://raw.githubusercontent.com/Sanidhya30/Jellyfin-Newsletter/master/logo.png"
version: "0.9.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Send newsletters for recently added media"
description: "This plugin populates a list of recently added media, sends out the messages to configured clients(email, discord webhook)."
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Newsletters.dll"
  - "SQLitePCL.pretty.dll"
  - "SixLabors.ImageSharp.dll"
changelog: >
  - Support for Jellyfin 10.11.x.
  FULL CHANGELOG: https://raw.githubusercontent.com/Sanidhya30/Jellyfin-Newsletter/master/CHANGELOG.md
